import type { BootstrapPayload } from "./types";

export const mockBootstrap: BootstrapPayload = {
  source: "mock",
  generatedAt: new Date().toISOString(),
  selectedConversationId: 1,
  stats: {
    instances: 1,
    conversations: 4,
    unread: 7,
    messages24h: 18,
  },
  conversations: [
    {
      conversation_id: 1,
      instance_id: 1,
      instance_name: "demo-instance",
      chat_jid: "51988877766@s.whatsapp.net",
      contact_jid: "51988877766@s.whatsapp.net",
      title: "Maria Gonzales",
      last_message_text: "¿Me confirmas el precio por 100 stickers?",
      last_message_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
      unread_count: 2,
      status: "open",
      assigned_to_user_id: "Felix",
      phone_number: "51988877766",
      display_name: "Maria Gonzales",
      push_name: "Maria",
      is_group: false,
    },
    {
      conversation_id: 2,
      instance_id: 1,
      instance_name: "demo-instance",
      chat_jid: "51999911122@s.whatsapp.net",
      contact_jid: "51999911122@s.whatsapp.net",
      title: "Juan Perez",
      last_message_text: "Gracias, mañana hago el abono.",
      last_message_at: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
      unread_count: 1,
      status: "open",
      assigned_to_user_id: null,
      phone_number: "51999911122",
      display_name: "Juan Perez",
      push_name: "Juan",
      is_group: false,
    },
    {
      conversation_id: 3,
      instance_id: 1,
      instance_name: "demo-instance",
      chat_jid: "51977733344@s.whatsapp.net",
      contact_jid: "51977733344@s.whatsapp.net",
      title: "Tienda Lima Norte",
      last_message_text: "¿Tienen delivery hoy en la tarde?",
      last_message_at: new Date(Date.now() - 1000 * 60 * 76).toISOString(),
      unread_count: 3,
      status: "pending",
      assigned_to_user_id: "Agente 2",
      phone_number: "51977733344",
      display_name: "Tienda Lima Norte",
      push_name: "Tienda Lima Norte",
      is_group: false,
    },
    {
      conversation_id: 4,
      instance_id: 1,
      instance_name: "demo-instance",
      chat_jid: "51966688800-123456@g.us",
      contact_jid: null,
      title: "Grupo - Cotizaciones",
      last_message_text: "Subo la muestra en PDF al grupo.",
      last_message_at: new Date(Date.now() - 1000 * 60 * 123).toISOString(),
      unread_count: 1,
      status: "open",
      assigned_to_user_id: null,
      phone_number: null,
      display_name: "Grupo - Cotizaciones",
      push_name: "Grupo - Cotizaciones",
      is_group: true,
    },
  ],
  messages: [
    {
      id: 11,
      instance_id: 1,
      contact_id: 1,
      conversation_id: 1,
      event_fingerprint: "mock-11",
      provider_message_id: "msg-11",
      event_type: "MESSAGE",
      direction: "inbound",
      chat_jid: "51988877766@s.whatsapp.net",
      sender_jid: "51988877766@s.whatsapp.net",
      receiver_jid: "51900000000@s.whatsapp.net",
      sender_name: "Maria",
      message_type: "conversation",
      message_text: "¿Me confirmas el precio por 100 stickers?",
      caption: null,
      message_status: "delivered",
      message_timestamp: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
      received_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
      from_me: false,
    },
    {
      id: 12,
      instance_id: 1,
      contact_id: 1,
      conversation_id: 1,
      event_fingerprint: "mock-12",
      provider_message_id: "msg-12",
      event_type: "MESSAGE",
      direction: "outbound",
      chat_jid: "51988877766@s.whatsapp.net",
      sender_jid: "51900000000@s.whatsapp.net",
      receiver_jid: "51988877766@s.whatsapp.net",
      sender_name: "Felix Vilchez",
      message_type: "conversation",
      message_text: "Claro, te envío la cotización en unos minutos.",
      caption: null,
      message_status: "read",
      message_timestamp: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
      received_at: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
      from_me: true,
    },
    {
      id: 13,
      instance_id: 1,
      contact_id: 1,
      conversation_id: 1,
      event_fingerprint: "mock-13",
      provider_message_id: "msg-13",
      event_type: "MESSAGE",
      direction: "inbound",
      chat_jid: "51988877766@s.whatsapp.net",
      sender_jid: "51988877766@s.whatsapp.net",
      receiver_jid: "51900000000@s.whatsapp.net",
      sender_name: "Maria",
      message_type: "conversation",
      message_text: "Perfecto, quedo atenta.",
      caption: null,
      message_status: "delivered",
      message_timestamp: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
      received_at: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
      from_me: false,
    },
  ],
};
